name: test-runner

run-name: Runs cypress tests.

on:
  workflow_dispatch:

jobs:
  run-cypress:
    runs-on:
      ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version:
            22.1.0
          cache: npm

      - name: Install Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Node stuff
        run: npm install

      - name: Start server and curl
        run: |
          python3 ./server.py 1> /dev/null
          curl http://localhost:8080/index.html | grep "Main"